version: '3.9'
services:
  # Define an LoudML+Tensorflow service
  loudml:
    depends_on:
      - "influxdb"
    image: loudml:latest
    environment:
      influx: http://192.168.86.30:8086
      influx_database: wp1
    volumes:
      - ./config.yml:/etc/loudml/config.yml
    ports:
      - "8077:8077"
      - "8887:8887"
